### ISSUE TITLE
raw_input is not defined

### ISSUE THREAD

**Issue by m4st3rP** [srgovindan/mal2csv#1]
When I try to run the script I get the following log messages claiming that raw_input is not defined.
I am using Python 3.8.3 on Windows 10.

python .\mal2csv.py

Script started.
Converting MAL Anime List.
Got XML file.
Traceback (most recent call last):
  File ".\mal2csv.py", line 15, in <module>
    path = raw_input('Please enter the file path of the export file in the format, .../animelist.csv :')
NameError: name 'raw_input' is not defined

**Comment by srgovindan** [comment]
Fixed on https://github.com/srgovindan/mal2csv/pull/2
